### PR TITLE
Avoid using deprecated hujson API

### PR DESCRIPTION
**Pull request by dsnet**
The hujson.Unmarshal function is deprecated.
Use hujson.Standardize instead.

The hujson package is evolving to be just a syntactic parser for HuJSON
and is moving away from semantically understanding HuJSON as Go data.

### CODE REVIEW

**Comment by dsnet** [comment]
The tests will fail since https://github.com/davidsbond/tailscale-client-go/pull/17 needs to be submitted first.

**Comment by davidsbond** [comment]
Thanks @dsnet, I'll get that dependency upgraded then we can merge this

**Comment by dsnet** [comment]
I updated to the latest version of `tailscale-client-go` in this PR. Up to you if you want to upgrade that dependency seperately.

**Comment by davidsbond** [comment]
Thanks, I think we need to do both in one PR as #103 fails the CI

**Pull request merged**
