### PR TITLE
add 'addresses' field to device and devices resources

### PR DESCRIPTION
**Pull request by kevinschoonover**
**What this PR does / why we need it**:
Adds  'addresses' to the `tailscale_device`and `tailscale_devices` resources for IP address lookups.

### CODE REVIEW

**Comment by davidsbond** [comment]
Hey @kevinschoonover, thanks for raising this. Would you mind adding some more context as to why you need this and how you intend to use it?

Right now you've just added it to the `device` data source, which is currently only obtainable by name, so you wouldn't be able to do an IP lookup on it.

**Comment by kevinschoonover** [comment]
Hey, I added it to both device and devices. Right now im using it to look up address of a specific tailscale node 
```terraform
provider "cloudflare" {}

data "cloudflare_zones" "default" {
  filter {
    name = var.domain
  }
}

data "tailscale_devices" "nomad_servers" {
  name_prefix = "do-sfo3-s-1vcpu-1gb-nomad-server"
}


resource "cloudflare_record" "nomad_servers" {
  zone_id = lookup(data.cloudflare_zones.default.zones[0], "id")
  name    = terraform.workspace == "prod" ? "nomad-servers" : "nomad-servers.${terraform.workspace}"
  value   = data.tailscale_devices.nomad_servers.devices[0].addresses[0]
  type    = "A"
  ttl     = 300
}

```

but added it to both incase someone wanted to do the same thing with a specific device

**Comment by davidsbond** [comment]
Ah that makes sense to me now.

Could you please update the documentation [here](https://github.com/davidsbond/terraform-provider-tailscale/blob/master/docs/data-sources/devices.md) as part of your PR?

I think it would also be good to update the `tailscale_device` data source as well to include the addresses

**Comment by davidsbond** [comment]
Also I need to figure out how to approve the tests to be ran

**Comment by davidsbond** [comment]
@kevinschoonover I've just updated the github actions flow to run on pull requests from forked repositories. Hopefully if you rebase I should then be able to approve running the CI for your pull request.

**Comment by kevinschoonover** [comment]
@davidsbond added the docks and rebased, let me know if you have any other comments

**Review by davidsbond — APPROVED** [review]
LGTM

**Comment by bilke** [comment]
@davidsbond May I ask you to push a release? Thanks a lot!

**Comment by davidsbond** [comment]
@bilke sure thing, I'll tag it now

**Comment by davidsbond** [comment]
I've tagged `v0.3.0`, the CI should take a couple minutes, then it'll take some more time for the terraform registry to sync the changes, but it should be ready for you fairly soon.

**Pull request merged**
